In [117]:
import tensorflow as tf

In [118]:
print(tf.__version__)

2.5.0


* Tensors: Multi deimensional array of uniform data type.

In [119]:
[6,2] # one dimensional array
[3,5]

[3, 5]

# constants:

* Are immutable i.e., fixed

In [120]:
# scalar
constant_1 = tf.constant(23.2)
constant_1

<tf.Tensor: shape=(), dtype=float32, numpy=23.2>

In [121]:
print(constant_1)

tf.Tensor(23.2, shape=(), dtype=float32)


In [122]:
# Array

array =[1,3,4]
const_2 = tf.constant(array) # tf over numpy is __ tf compute on defualt device. but numpy wont  
const_2
#here the shape is array of 3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4])>

In [123]:
array = [[1,3,4]] # became matriy  format_row matrix
const_3 =tf.constant(array)
const_3
#here in the op we had 1*3 matrix

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 3, 4]])>

In [124]:
# converting this constants into numpy
type(const_3.numpy())

numpy.ndarray

In [125]:
type(const_3)

tensorflow.python.framework.ops.EagerTensor

In [126]:
const_3.shape # like numpy can check the shape

TensorShape([1, 3])

In [127]:
const_3.dtype

tf.int32

In [128]:
# generating numbers
import numpy as np
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
tf.ones(shape=(3,3)) # we can use them while introducing bias in input layers.

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [131]:
tf.ones(shape=(3,3))*3 # multiply with any number

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [132]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

 ## Operarions

In [133]:
const_1 = tf.constant([[1,2],[5,7]])
const_2 = tf.constant([[3,2],[5,8]])
const_1 + const_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  4],
       [10, 15]])>

In [134]:
tf.add(const_1, const_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  4],
       [10, 15]])>

In [135]:
x = tf.random.normal(shape=(2,2), mean=0,stddev=1.0) # generating random values
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.195879 , -1.4832753],
       [-1.4693323, -1.1220293]], dtype=float32)>

In [136]:
y = tf.random.uniform(shape=(2,3),
                 minval = 0,
                 maxval = 30,
                 dtype=tf.int32) # random uniform distribution
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3, 22,  3],
       [15,  8, 10]])>

In [137]:
#tf.constant  are immutable

## lets defined variable

* mutable

In [138]:
var_0 = tf.Variable([4,6])
var_0

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6])>

In [139]:
var_0[0].assign(22) # 0 =4,1=6

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([22,  6])>

##### assigning a values to variables

In [140]:
var_0[0].assign(22)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([22,  6])>

In [141]:
# shape of the tensors
array = [[1,2]]
var_1 = tf.Variable(array)
var_1

<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 2]])>

In [142]:
tf.reshape(var_1,[2,1])

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [143]:
tensor = tf.Variable ([[[1,2,7],[3,4,6],[5,6,9]]
                       ,[[7,8,9],[1,2,3],[3,6,7]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[1, 2, 7],
        [3, 4, 6],
        [5, 6, 9]],

       [[7, 8, 9],
        [1, 2, 3],
        [3, 6, 7]]])>

## Buit in datatypes in tensor_flow

`TensorFlow has a large number of built-in datatypes.`

datatype | description
- | -
 tf.float16 | 16-bit half-precision floating-point.
 tf.float32 | 32-bit single-precision floating-point.
 tf.float64 | 64-bit double-precision floating-point.
 tf.bfloat16 | 16-bit truncated floating-point.
 tf.complex64 | 64-bit single-precision complex.
 tf.complex128 | 128-bit double-precision complex.
 tf.int8 | 8-bit signed integer.
 tf.uint8 | 8-bit unsigned integer.
 tf.uint16 | 16-bit unsigned integer.
 tf.uint32 | 32-bit unsigned integer.
 tf.uint64 | 64-bit unsigned integer.
 tf.int16 | 16-bit signed integer.
 tf.int32 | 32-bit signed integer.
 tf.int64 | 64-bit signed integer.
 tf.bool | Boolean.
 tf.string | String.
 tf.qint8 | Quantized 8-bit signed integer.
 tf.quint8 | Quantized 8-bit unsigned integer.
 tf.qint16 | Quantized 16-bit signed integer.
 tf.quint16 | Quantized 16-bit unsigned integer.
 tf.qint32 | Quantized 32-bit signed integer.
 tf.resource | Handle to a mutable resource.
 tf.variant | Values of arbitrary types.

* mostly we use float 32 and float 64
* when we change to higher floating point ?
 * ans_1: to get more high precious decesion
 * ans_2 :in image classification we need higher precision.       
        

In [144]:
tensor_1 = tf.reshape(tensor,[3,6]) # 3 rows and each tensor has 6 elements in it.
tensor_1

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[1, 2, 7, 3, 4, 6],
       [5, 6, 9, 7, 8, 9],
       [1, 2, 3, 3, 6, 7]])>

In [145]:
tensor_2 =tf.reshape(tensor,[6,3])
tensor_2

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 7],
       [3, 4, 6],
       [5, 6, 9],
       [7, 8, 9],
       [1, 2, 3],
       [3, 6, 7]])>

In [146]:
# rank of tensors: number
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [147]:
tf.rank(tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [148]:
tf.rank(tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [149]:
# how to get particular element in the tensor :?
tensor
    

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[1, 2, 7],
        [3, 4, 6],
        [5, 6, 9]],

       [[7, 8, 9],
        [1, 2, 3],
        [3, 6, 7]]])>

In [150]:
tensor[1,0,1] # 1_ second matrix, 0_ first row in second matrix, 1_ 2nd element= 8

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [151]:
#now lets try for 6 in first matrix
tensor[0,1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [152]:
tensor_2

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 7],
       [3, 4, 6],
       [5, 6, 9],
       [7, 8, 9],
       [1, 2, 3],
       [3, 6, 7]])>

In [153]:
tensor_2[3,1]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [154]:
tf.rank(tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [155]:
tensor[1]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [3, 6, 7]])>

In [156]:
tensor[1,:,0] # to get only column

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 1, 3])>

In [157]:
tensor[1,1:,0] # slicing element

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

In [158]:
tensor[1,:,0].numpy()

array([7, 1, 3])

In [159]:
# size of tensors
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

## Mathematical operations

In [160]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))


In [161]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7775275 ,  0.04628835],
       [ 0.4744778 , -2.3889418 ]], dtype=float32)>

In [162]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.2236673,  0.7647063],
       [ 1.0275142,  1.1802356]], dtype=float32)>

In [163]:
c = a+b
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0011947,  0.8109947],
       [ 1.501992 , -1.2087061]], dtype=float32)>

In [164]:
tf.square(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.0047803, 0.6577124],
       [2.25598  , 1.4609705]], dtype=float32)>

In [165]:
tf.exp(c) # exponential

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.1351737 , 2.250145  ],
       [4.4906254 , 0.29858336]], dtype=float32)>

In [166]:
d = a * b
d # gives dot product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.95143497,  0.03539699],
       [ 0.48753268, -2.8195143 ]], dtype=float32)>

In [167]:
 a @ b # matrix multiplication # if both shapes are not equal we may get error.

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.9989969, -0.539949 ],
       [-3.0352745, -2.4566782]], dtype=float32)>

In [168]:
e = tf.random.normal(shape=(2,3))
e


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.49527025,  0.40811   , -1.3759644 ],
       [ 0.22492634, -1.1384691 , -0.18679348]], dtype=float32)>

In [169]:
tf.transpose(e) @ a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.27836367, -0.5144107 ],
       [-0.85749507,  2.738627  ],
       [ 0.98122084,  0.38254762]], dtype=float32)>

In [170]:
# can be done
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.9989969, -0.539949 ],
       [-3.0352745, -2.4566782]], dtype=float32)>

In [171]:
tf.matmul(tf.transpose(e),a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.27836367, -0.5144107 ],
       [-0.85749507,  2.738627  ],
       [ 0.98122084,  0.38254762]], dtype=float32)>

In [172]:
# broadcasting values
scalar = 5
tensor * scalar # multiplication to each element in the tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 5, 10, 35],
        [15, 20, 30],
        [25, 30, 45]],

       [[35, 40, 45],
        [ 5, 10, 15],
        [15, 30, 35]]])>

In [173]:
# casting
tensor.dtype

tf.int32

In [174]:
i = tf.cast(tensor, dtype= tf.float32)
i

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 2., 7.],
        [3., 4., 6.],
        [5., 6., 9.]],

       [[7., 8., 9.],
        [1., 2., 3.],
        [3., 6., 7.]]], dtype=float32)>

In [175]:
i = tf.cast(tf.Variable(444.999), dtype= tf.int32)
i


<tf.Tensor: shape=(), dtype=int32, numpy=444>

## Ragged tensors:
    A ragged tensor is a tensor having one or more ragged dimensions. Its nothing but TensorFlow equivalent of nested variable-length lists. Ragged dimensions are dimensions that have slices having various lengths. There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array
    
   * equivalent to nested variable legnths
   * Make easy to store and process data with non-uniform shapes

In [176]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]]) # have 5 elements
print(ragged.shape)


(5, None)


In [177]:
print(ragged[0,:].shape)
print(ragged[1,:].shape)
print(ragged[2,:].shape)
print(ragged[3,:].shape)
print(ragged[4,:].shape)

(4,)
(0,)
(3,)
(1,)
(2,)


In [178]:
var_x = [4,5,6,7,2,1] 
var_y = 9
var_z = tf.math.squared_difference(var_x,var_y)
var_z

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([25, 16,  9,  4, 49, 64])>

In [179]:
pred = [4,5,6,7,2,1] 
actual = [16,5,10,2,3,6]
squared_error = tf.math.squared_difference(pred,actual)
squared_error

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([144,   0,  16,  25,   1,  25])>

In [180]:
tf.reduce_mean(squared_error) # mean sq_error

<tf.Tensor: shape=(), dtype=int32, numpy=35>

In [183]:
# ' defining constants'
numbers = tf.constant([[8.,9.],
                       [1.,2.]])


In [184]:
tf.reduce_mean(input_tensor = numbers, axis = 0) # column wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

In [185]:
tf.reduce_mean(input_tensor = numbers, axis = 1) # row wise

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [186]:
tf.reduce_mean(input_tensor = numbers) # adding all of them

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [189]:
#keeping the dimension
tf.reduce_mean(input_tensor = numbers, axis = 0,keepdims = True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

In [192]:
x = tf.random.normal(shape = (3,2),
                mean = 10,
                stddev = 2,
                dtype = tf.float32,
                seed = 40,  #
                name = "randomNormalTensor")
print(x)

tf.Tensor(
[[ 9.178438  9.303067]
 [ 9.617221  8.399563]
 [10.619968 10.862235]], shape=(3, 2), dtype=float32)


In [197]:
tf.random.set_seed(11)
x = tf.random.normal(shape = (3,2),
                mean = 10,
                stddev = 2,
                dtype = tf.float32,
                seed = 40,  #
                name = "randomNormalTensor")
print(x)

tf.Tensor(
[[ 9.8125925  9.90883  ]
 [11.110067  13.150067 ]
 [ 8.053195  10.57778  ]], shape=(3, 2), dtype=float32)


* while performing numereous data without changing environment. only you can change the parameters
* ex: in program u just need to change the activation fun not the whole program..then u can keep the environment same by adding seeds and only need to chnage the required activation fun.


In [205]:
# argmax
dice1 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval= 7,dtype= tf.int32))
dice1

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[5],
       [4],
       [5],
       [3],
       [1],
       [4],
       [5],
       [6],
       [3],
       [2]])>

In [206]:
dice1[tf.argmax(dice1).numpy()[0]]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>

In [208]:
dice1[tf.argmin(dice1).numpy()[0]]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [209]:
# saving and restoring checkpoints

variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
print(variable1)

checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars') # file saving in binary format

variable1.assign([[0,0,0,0],[0,0,0,0]])
print(variable1)

checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


#### Using tf.function

`tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.`


In [211]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
    
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

In [212]:
@tf.function
def f2(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)

In [213]:
assert f2(x,y).numpy() == func(x,y).numpy()

In [220]:
def decorate_it(input_func):
    def decorated_func():
        print("#"*100)
        input_func()
        print("#"*100)

    return decorated_func

def func():
    print("Hey buddie")

In [221]:
func()

Hey buddie


In [222]:
decorated = decorate_it(func)
decorated()

####################################################################################################
Hey buddie
####################################################################################################


# calculating gradient

## Gradient Tape

* Another difference from numpy is that it can automatically track the gradient of any variable.

* Open one GradientTape and tape.watch() track variables through

In [224]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[ 0.80331576 -0.71973795]
 [-0.58444905 -0.7099158 ]], shape=(2, 2), dtype=float32)


In [225]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    # tape.watch(a) # returns None if not used 
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

None


In [226]:
a = tf.random.normal(shape=(1,2))
print(a)
b = tf.random.normal(shape=(1,2))
print(b)

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.square(a)
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor([[1.6636649 0.8449321]], shape=(1, 2), dtype=float32)
tf.Tensor([[-0.41427493  0.27209428]], shape=(1, 2), dtype=float32)
tf.Tensor([[3.3273299 1.6898642]], shape=(1, 2), dtype=float32)


In [227]:
2*a

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3.3273299, 1.6898642]], dtype=float32)>

In [228]:
# from IPython.display import display, Math
# display(Math(r'x^2 + y^2'))

>For all variables, the calculation is tracked by default and used to find the gradient, so do not `use tape.watch()`

In [229]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor([[0.9703674  0.95186144]], shape=(1, 2), dtype=float32)


> You can GradientTapefind higher-order derivatives by opening a few more:


In [232]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor([[0.03405553 0.10585093]], shape=(1, 2), dtype=float32)


In [233]:
a = tf.random.normal(shape=(2,2))
a = tf.Variable(a)
print(a)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.square(a)
        dc_da = tape.gradient(c,a)
        print(dc_da)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.10532369,  2.5562282 ],
       [-1.5410595 , -1.4889685 ]], dtype=float32)>
tf.Tensor(
[[-0.21064739  5.1124563 ]
 [-3.082119   -2.977937  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
